// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	utils "github.com/gendocu-com/rpc-invoker/pkg/utils"
)

// DocRepo is an autogenerated mock type for the DocRepo type
type DocRepo struct {
	mock.Mock
}

// GetUrl provides a mock function with given fields: ctx, buildId, serviceName, envName
func (_m *DocRepo) GetUrl(ctx context.Context, buildId utils.BuildId, serviceName utils.ServiceName, envName utils.EnvName) (*utils.GPRCUrl, error) {
	ret := _m.Called(ctx, buildId, serviceName, envName)

	var r0 *utils.GPRCUrl
	if rf, ok := ret.Get(0).(func(context.Context, utils.BuildId, utils.ServiceName, utils.EnvName) *utils.GPRCUrl); ok {
		r0 = rf(ctx, buildId, serviceName, envName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.GPRCUrl)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, utils.BuildId, utils.ServiceName, utils.EnvName) error); ok {
		r1 = rf(ctx, buildId, serviceName, envName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
